trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: "Build and Test"
    jobs:
      - job: Build
        steps:
          - task: UseJavaVersion@1
            inputs:
              versionSpec: '17'
              jdkArchitecture: 'x64'

          - script: mvn clean package
            displayName: "Build Java App"

          - script: mvn test
            displayName: "Run Unit Tests"

          - script: mvn checkstyle:check
            displayName: "Lint Code"

  - stage: Docker
    displayName: "Docker Build & Push"
    dependsOn: Build
    jobs:
      - job: DockerBuildPush
        steps:
          - task: Docker@2
            displayName: "Login to DockerHub"
            inputs:
              command: "login"
              containerRegistry: "DockerHubServiceConnection"  # Set up in Azure DevOps

          - script: docker build -t simple-java-app .
            displayName: "Build Docker Image"

          - script: docker tag simple-java-app $(DOCKER_ID)/simple-java-app:latest
            displayName: "Tag Docker Image"

          - script: docker push $(DOCKER_ID)/simple-java-app:latest
            displayName: "Push Docker Image"

  - stage: Deploy
    displayName: "Deploy Application"
    dependsOn: Docker
    jobs:
      - job: Deploy
        steps:
          - script: echo "Deploying application..."
            displayName: "Deploy App"
